### ISSUE TITLE
4.0.0 Release

### ISSUE THREAD

**Issue by whatknight** [jdlehman/switcheroo#29]
@jdlehman Lets use this to track what we need to do for the 4.0.0 release
# Todo for 4.0.0
- [ ] refactor context provider design to remove need for consumer to manage listener lists
- [ ] top level api changes - we need to reconsider the public api to reduce its surface area and make it more predictable

# nice to have
- [ ] public hook api?
- [ ] functional tests for pop state and hash change since these are browser dependent and using jsdom doesnt quite cut it?
